name: taskify
description: A Flutter task manager application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  timezone: ^0.10.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  file_picker: ^10.1.9
  window_manager: ^0.5.0
  flutter_local_notifications: ^19.1.2
  uuid: ^4.5.1
  share_plus: ^11.0.0
  mobile_scanner: ^7.0.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  network_info_plus: ^6.1.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#7E57C2"
  adaptive_icon_foreground: "assets/foreground_icon.png"
  adaptive_icon_round: true
  min_sdk_android: 21