name: Taskify CI/CD

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'  
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze

  build-android:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Store APK for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p releases
          cp build/app/outputs/flutter-apk/app-release.apk releases/taskify-${{ github.ref_name }}.apk

  build-ios:
    needs: analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      - run: flutter create --platforms=ios . || true
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload
      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app.ipa
      - name: Store IPA for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p releases
          cp build/ios/iphoneos/app.ipa releases/taskify-${{ github.ref_name }}.ipa

  build-windows:
    needs: analyze
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      - run: flutter config --enable-windows-desktop
      - run: flutter create --platforms=windows . || true
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release
      - name: Store Windows build for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir releases
          Compress-Archive -Path "build/windows/x64/runner/Release/*" -DestinationPath "releases/taskify-${{ github.ref_name }}-windows.zip"

  build-linux:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      - run: flutter config --enable-linux-desktop
      - run: flutter create --platforms=linux . || true
      - run: flutter pub get
      - run: flutter build linux --release
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle
      - name: Store Linux build for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p releases
          cd build/linux/x64/release/bundle
          tar czf ../../../../../releases/taskify-${{ github.ref_name }}-linux.tar.gz *

  build-macos:
    needs: analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      - run: flutter config --enable-macos-desktop
      - run: flutter create --platforms=macos . || true
      - run: flutter pub get
      - run: flutter build macos --release
      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release
      - name: Store macOS build for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p releases
          cd build/macos/Build/Products/Release
          zip -r ../../../../../releases/taskify-${{ github.ref_name }}-macos.zip ./*

  create-release:
    needs: [build-android, build-ios, build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      # Создаем директорию для артефактов
      - name: Create Releases directory
        run: mkdir -p releases

      # Скачиваем все артефакты из предыдущих jobs
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: downloaded

      # Подготавливаем файлы для релиза
      - name: Prepare release files
        run: |
          mkdir -p release_files
          cp downloaded/android-apk/app-release.apk release_files/taskify-${{ github.ref_name }}.apk
          cp downloaded/ios-ipa/app.ipa release_files/taskify-${{ github.ref_name }}.ipa
          cp downloaded/windows-build/windows-release.zip release_files/taskify-${{ github.ref_name }}-windows.zip
          cp downloaded/linux-build/linux-release.tar.gz release_files/taskify-${{ github.ref_name }}-linux.tar.gz
          cp downloaded/macos-build/macos-release.zip release_files/taskify-${{ github.ref_name }}-macos.zip
          ls -la release_files/

      # Создаем релиз
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release_files/taskify-${{ github.ref_name }}.apk
            release_files/taskify-${{ github.ref_name }}.ipa
            release_files/taskify-${{ github.ref_name }}-windows.zip
            release_files/taskify-${{ github.ref_name }}-linux.tar.gz
            release_files/taskify-${{ github.ref_name }}-macos.zip
          name: Taskify ${{ github.ref_name }}
          body: |
            ## Taskify Release ${{ github.ref_name }}
            
            ### Downloads
            - [Android] taskify-${{ github.ref_name }}.apk
            - [iOS] taskify-${{ github.ref_name }}.ipa
            - [Windows] taskify-${{ github.ref_name }}-windows.zip
            - [Linux] taskify-${{ github.ref_name }}-linux.tar.gz
            - [macOS] taskify-${{ github.ref_name }}-macos.zip
            
            ### Build Information
            - Build Date: ${{ github.event.head_commit.timestamp }}
            - Commit: ${{ github.sha }}
          draft: false
          prerelease: false
          generate_release_notes: true